-- Week 1: SnowMind structured + unstructured foundations

CREATE DATABASE IF NOT EXISTS SNOWMIND_DB;
CREATE SCHEMA IF NOT EXISTS SNOWMIND_DB.SALES;
CREATE SCHEMA IF NOT EXISTS SNOWMIND_DB.USERS;
CREATE SCHEMA IF NOT EXISTS SNOWMIND_DB.EVENTS;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE DATABASE SNOWMIND_DB;
USE WAREHOUSE COMPUTE_WH;

-- File formats
CREATE OR REPLACE FILE FORMAT FF_CSV
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE FILE FORMAT FF_JSON
  TYPE = JSON;

-- Local-to-cloud stage targets
CREATE OR REPLACE STAGE STG_STRUCTURED;
CREATE OR REPLACE STAGE STG_UNSTRUCTURED;

-- Structured tables
CREATE OR REPLACE TABLE SALES.ORDERS (
  order_id STRING,
  order_date DATE,
  customer_id STRING,
  amount NUMBER(12,2),
  region STRING
);

CREATE OR REPLACE TABLE USERS.PROFILES (
  user_id STRING,
  signup_date DATE,
  country STRING,
  segment STRING
);

CREATE OR REPLACE TABLE EVENTS.APP_EVENTS (
  payload VARIANT,
  ingested_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Sample COPY INTO templates
-- COPY INTO SALES.ORDERS
--   FROM @STG_STRUCTURED/orders.csv
--   FILE_FORMAT = (FORMAT_NAME = FF_CSV)
--   ON_ERROR = CONTINUE;

-- COPY INTO USERS.PROFILES
--   FROM @STG_STRUCTURED/users.csv
--   FILE_FORMAT = (FORMAT_NAME = FF_CSV)
--   ON_ERROR = CONTINUE;

-- COPY INTO EVENTS.APP_EVENTS(payload)
--   FROM @STG_STRUCTURED/events/
--   FILE_FORMAT = (FORMAT_NAME = FF_JSON)
--   ON_ERROR = CONTINUE;

-- Validation queries
-- SELECT COUNT(*) FROM SALES.ORDERS;
-- SELECT COUNT(*) FROM USERS.PROFILES;
-- SELECT COUNT(*) FROM EVENTS.APP_EVENTS;
