-- Optional Week 2 setup: Cortex Search service

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWMIND_DB;
USE SCHEMA CORTEX;

CREATE OR REPLACE CORTEX SEARCH SERVICE KB_SEARCH
  ON content
  ATTRIBUTES category, title
  WAREHOUSE = COMPUTE_WH
  TARGET_LAG = '5 minutes'
AS
SELECT doc_id, title, category, content
FROM KNOWLEDGE_BASE;
