-- Run these after uploading files to stage

-- 1) Upload local files to structured stage from SnowSQL CLI:
-- PUT file://./data/structured/orders.csv @SNOWMIND_DB.PUBLIC.STG_STRUCTURED AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- PUT file://./data/structured/users.csv @SNOWMIND_DB.PUBLIC.STG_STRUCTURED AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- PUT file://./data/structured/events.json @SNOWMIND_DB.PUBLIC.STG_STRUCTURED/events AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- 2) Upload local docs to unstructured stage:
-- PUT file://./data/unstructured/*.pdf @SNOWMIND_DB.PUBLIC.STG_UNSTRUCTURED AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
-- PUT file://./data/unstructured/*.md @SNOWMIND_DB.PUBLIC.STG_UNSTRUCTURED AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- 3) Copy staged files into tables:
COPY INTO SNOWMIND_DB.SALES.ORDERS
  FROM @SNOWMIND_DB.PUBLIC.STG_STRUCTURED/orders.csv
  FILE_FORMAT = (FORMAT_NAME = SNOWMIND_DB.PUBLIC.FF_CSV)
  ON_ERROR = CONTINUE;

COPY INTO SNOWMIND_DB.USERS.PROFILES
  FROM @SNOWMIND_DB.PUBLIC.STG_STRUCTURED/users.csv
  FILE_FORMAT = (FORMAT_NAME = SNOWMIND_DB.PUBLIC.FF_CSV)
  ON_ERROR = CONTINUE;

COPY INTO SNOWMIND_DB.EVENTS.APP_EVENTS(payload)
  FROM @SNOWMIND_DB.PUBLIC.STG_STRUCTURED/events
  FILE_FORMAT = (FORMAT_NAME = SNOWMIND_DB.PUBLIC.FF_JSON)
  ON_ERROR = CONTINUE;

-- 4) Validate load:
SELECT 'orders' AS table_name, COUNT(*) AS row_count FROM SNOWMIND_DB.SALES.ORDERS
UNION ALL
SELECT 'profiles' AS table_name, COUNT(*) AS row_count FROM SNOWMIND_DB.USERS.PROFILES
UNION ALL
SELECT 'events' AS table_name, COUNT(*) AS row_count FROM SNOWMIND_DB.EVENTS.APP_EVENTS;
